### ISSUE TITLE
(conversa inicial) Planejamento para desenvolvimento do site do Training Center

### ISSUE THREAD

**Issue by woliveiras** [training-center/training-center.github.io#1]
# Alinhamento

Essa issue servirá para discussão sobre criação de um site para o Training Center e seus projetos.

O Training Center possui, hoje, as informações a respeito dos projetos através dos repositórios GitHub:
- https://github.com/training-center/mentoria < mais ativo
- https://github.com/training-center/study-groups
- https://github.com/training-center/dojos
- https://github.com/training-center/sobre < sobre nós
- https://github.com/training-center/projects
- https://github.com/training-center/materials

Precisamos desenvolver um site para centralizar todas essas informações.

Hoje temos a seguinte página: https://training-center.github.io/

E já começamos o planejamento de um site na issue: https://github.com/training-center/study-groups/issues/46

**Vamos mover a discussão pra cá!**
## O que precisamos?

Precisamos de um site institucional para que as pessoas conheçam o Training Center com as informações do repositório `sobre-nos` e algumas páginas internas sobre os projetos.

Em suas páginas internas precisaremos de uma maior interação.
## Páginas sugeridas
- Mentoria
- Study Groups

Na página do **Mentoria** pensamos coletar dados do GitHub para exibir as issues abertas e poder filtrar por labels, também precisamos buscar lista de Mentores e Pupilos cadastrados (podendo ser via JSON).

Na página do **Study Groups** precisamos destacar quem está participando dos grupos de alguma maneira para animar as pessoas por estarem estudando. Talvez um esquema de badge ou subir de posição em um hanking baseado em alguma pontuação.
## Estrutura

Podemos seguir o esquema usado no projeto `Eventos` do [FrontEndBR](https://github.com/frontendbr/eventos/issues/3).
- Um arquivo JSON vai receber os dados dos Mentores que serão preenchidos via PR pelos próprios novos Mentores.
- Tendo o arquivo, um esquema de template renderiza a lista com paginação, filtros e uma boa usabilidade para o usuário final
- Devemos seguir o esquema das labels ([Mentoria](https://github.com/training-center/mentoria/labels), [Study Groups](https://github.com/training-center/study-groups/labels)) para os filtros no site para haver consistência entre o que já fazemos com o novo fluxo
## Tecnologias

Devemos discutir isso nessa issue com base em quem poderá ajudar o projeto.
## Checklist
- [ ] Criação de estrutura do projeto com definição de diretórios
- [ ] Modificações no layout para estruturar as novas páginas
- [ ] Configuração de task runner
- [ ] Criação do html + css - ainda sem integração com JSON
- [ ] Script pra ler o JSON e renderizar o template
- [ ] Script pra filtros (labels aqui do repo, preço, local)
- [ ] Paginação

Bora agitar, @training-center/mentors  @training-center/pupils  @training-center/moderators  @training-center/study-groups

**Comment by baltazarparra** [comment]
Vou redesenhar algumas coisas do primeiro layout que fiz, logo menos posto aqui o resultado, para possíveis alterações/otimizações junto aos amigos. @woliveiras @danilovaz @KarolinedeAlencar

**Comment by danilovaz** [comment]
Bora lá! :heart: :tada:

Alguém já teve experiência com a mesma estrutura do FrontEndBR? Me parece uma boa, não sei ao certo porque não tive muita experiência com milligram e preact.

@baltazarparra O que acha da listagem do Mentoria ser algo parecido com [isso](http://ogilvieira.com.br/awesome-podcasts-br/#/) ? Me parece uma forma bem fácil de ir filtrando mentores disponíveis e quem precisa de mentoria. Poderíamos até criar algo onde os próprios mentores colocam seu status como `Disponível` e `Indisponível` para sabermos quem ainda tem "vaga" pra mentorar.

**Comment by hugoalmeidahh** [comment]
Opá, to dentro... seria legal fazer um hangout para conversarmos e alinharmos melhor essas informaçoes e o pensamento de cada um... "Brasinstorm".... kkkkk

**Comment by teles** [comment]
Issue bem especificada :D 
Vou tentar dar palpite, se for relevante, até terça.

**Comment by WendellAdriel** [comment]
Temos muitas tecnologias para escolher hehehehhe. Pessoalmente acho que ficaria legal em fazer com React/Preact ou Vue.js

**Comment by woliveiras** [comment]
Seria bom esse esquema de disponível ou não ein @danilovaz

**Comment by woliveiras** [comment]
Vejo muito conteúdo de React, mas ainda nem comecei a mexer com ele.

Se tiver alguém manjador de React pra ir botando ordem na casa, seria interessante utilizar a lib.

Podemos aprender enquanto desenvolvemos algo legal. 👍

**Comment by woliveiras** [comment]
A ideia do Hangout seria show @hhalmeida 

Assim que tiver mais gente da pra marcar mesmo.

**Comment by danilovaz** [comment]
Sobre React/Preact eu sou a favor, desde que, assim como o @woliveiras disse: tenha alguém que possa nos ajudar nas melhores práticas e caminhos. Assim não perdemos tempo quebrando a cabeça com errinhos. Quem aí é manjador de React?

Sobre o hangouts, seria mais produtível depois de fecharmos a estrutura/tecnologia. Aí reunimos todos pra separar atividades.

**Comment by ghost** [comment]
Não me considero "manjador"/especialista em React, mas já quebrei a cabeça com algumas coisas e posso ajudar um pouco.

**Comment by baltazarparra** [comment]
Vamos separar em grupos, acho que rola uma melhor organização desta forma, não?
Eu cuido da parte visual/interface/usabilidade, se alguém quiser dar um help com isso, será muito bem vindo. E como vamos organizar o desenvolvimento? Acho que é cedo pra tecnologias, não temos um escopo definido, por mim tocava o vanilla em tudo kkkk,  seus moderninhos.

Seguindo a linha que o mano @danilovaz começou, vamos organizar primeiro as features que vamos contemplar na primeira release. Oque acham?

**Comment by vicainelli** [comment]
Que tal já implementar o [yarn](https://github.com/yarnpkg/yarn)?

**Comment by vicainelli** [comment]
@baltazarparra concordo contigo, e posso ajudar com UX tb.

**Comment by hugoalmeidahh** [comment]
Olha, acho que seria interessante pensarmos no [NG2](angular.io), kkkkk , Brinks não me batam...!
Podemos pensar em Ember mesmo, aceito de bom grado! rsrs!

@baltazarparra, seria legal, mas se já definirmos a tecnologia, já ajuda a pensar nas possibilidades do escopo pela tecnologia.

Penso que poderiamos escalar, usar o github (io pages), firebase, openshift ... sugestões!

**Comment by baltazarparra** [comment]
@vicainelli Nice... você chegou a ver o primeiro layout? já faz um tempo que eu fiz, e foi chutadão, mas acho que dá pra trampar em cima dele. [layout](http://baltazarparra.github.io/ct-layout.html)

**Comment by baltazarparra** [comment]
@hhalmeida Ainda não sabemos nem as features, não vejo uma forma de pensar sobre oque vamos usar, sem antes escopar as funcionalidades.

**Comment by hugoalmeidahh** [comment]
Muuutio doido esse layout, curti ele @baltazarparra ... parabéns... 
Estou disponivel para ser o bombril... podem contar comigo.. rsrs

**Comment by baltazarparra** [comment]
@hhalmeida Valeu man =] vamos melhor ele, muito ainda.

**Comment by woliveiras** [comment]
@vicainelli muito cedo mano...

Vamos esperar as pessoas quebrarem a cabeça com ele antes. kkkk

Fora que NPM deve atender bem as necessidades (que ainda não sabemos) viu cara.

**Comment by woliveiras** [comment]
@baltazarparra as features estão na issue aqui homi. 😂

**Comment by vicainelli** [comment]
Vi sim @baltazarparra bora começar.
Acho válido criar uma issue pra cada um desses itens do [check list](#issue-183094384), assim separamos os assuntos.

@woliveiras Pensei nisso agora man, é empolgação haha.. faz sentido mesmo o que disse.

**Comment by woliveiras** [comment]
Bem pensado @vicainelli 

O que acham, galera, criamos uma issue pra cada assunto?

**Comment by baltazarparra** [comment]
@woliveiras eu vi sim homi, kkkk, mas tipo, Ex. a ideia que o @danilovaz deu, é bem válida, então, acho que podem surgir mais nessa linha, antes de fecharmos o escopo.

**Comment by baltazarparra** [comment]
@vicainelli uma issue pra cada item, seria ótimo, e tipo, deixa pra criar a prox. quando a atual for finalizada. Oque acham?

**Comment by vicainelli** [comment]
Uma boa, assim temos um fluxo mais organizado.

**Comment by andre-mendes** [comment]
esse layout ta lindao :dancer:

**Comment by baltazarparra** [comment]
@andre-mendes vlw man o/

**Comment by rodrigooler** [comment]
Ficou irado o layout @baltazarparra !

**Comment by jlucfarias** [comment]
Se precisarem de ajuda com UI/UX podem contar comigo, não sou tão manjador, mas quebro um galho

**Comment by rodrigooler** [comment]
Se precisarem de ajuda estou disponível no que for necessário!

**Comment by metractive** [comment]
E ai pessoal, acompanhava a outra issue. Concordo sobre separar por issues, curti desde a primeira versão do layout @baltazarparra!

Não manjo de design, me aventuro mais no front e back. Mas se precisarem desenvolver algum back mesmo que seja mínimo nessa estrutura que montaram, to dentro! Também vou postando opiniões que for pensando.

**Comment by woliveiras** [comment]
Show! 

Vou separar por issues então.

Já tenho uma ideia do que fazer.

Aguardem novidades até a noite! 😄 

Enquanto isso podem mandar ideias aqui.

**Comment by brunooomelo** [comment]
se precisarem de ajuda, estou aqui :D

**Comment by rodrigooler** [comment]
Quem estiver acostumado com board podem utilizar o [ZenHub](https://www.zenhub.com/) ou [Waffle](https://waffle.io/) super recomendo! :)

**Comment by danilovaz** [comment]
Seria melhor usar o Projects, do Github mesmo, não?

**Comment by vicainelli** [comment]
Bem lembrado @danilovaz.

**Comment by danilovaz** [comment]
quanto mais centralizar as tarefas/discussões aqui, melhor. mantém um histórico pra futuras consultas etc

**Comment by jlucfarias** [comment]
Concordo com o @danilovaz melhor deixar tudo aqui no github mesmo

**Comment by rodrigooler** [comment]
@danilovaz justamente por usarmos o Github o ZenHub/Waffle são ferramentas para os contribuintes que quiserem usar.

**Comment by danilovaz** [comment]
@RodrigoOler Sim sim, concordo. Mas não seria melhor usar [aqui](https://github.com/training-center/training-center.github.io/projects) ???

**Comment by rodrigooler** [comment]
@danilovaz sim, eu particularmente estou acompanhando a issue aqui através do ZenHub.

**Comment by danilovaz** [comment]
@RodrigoOler Eu não vejo problemas em utilizar ferramentas de terceiros pra gerenciar as tarefas, mas talvez seja mais benéfico utilizar o "nativo" do Projects, até porque seria um aprendizado mais fácil do que ter que fazer todo mundo aqui criar uma conta nessas ferramentas. Também não usei o Projects ainda, mas pelo que vi é simples e já tá aqui no Repo :smile:

**Comment by rodrigooler** [comment]
@danilovaz também não vejo problemas, também não usei o Projects mas no caso como você disse é simples é melhor.

**Comment by rodrigooler** [comment]
@danilovaz estou dando uma olhada aqui no Projects é bem show, é até melhor do que usar ferramentas de terceiros para gerenciar tarefas.

**Comment by YuriBrunetto** [comment]
Excelente iniciativa, pessoal ❤️ 

Posso ajudar com CSS e com o que mais precisarmos também 😆

**Comment by mtmr0x** [comment]
Alguem falou React? 👀  To num projeto imenso com NodeJS + React usando o Webpack e ES6 em tudo (server e client, parada sinistra).

Essa parte de "infra" e setup de task runner, automatização, back end e etc, se precisarem, tenho bastante xp. :)

Sendo prático, pessoal de SP aqui podia se trombar pela paulista um dia. Adiantamos umas coisas

**Comment by woliveiras** [comment]
Galera, bora discutir em cada issue pelo assunto, agora! :metal:

**Comment by woliveiras** [comment]
Criei tudo em issues separadas e vamos defini-las melhor pra ficar fácil a organização via Projects aqui no GitHub.

**Comment by ogilvieira** [comment]
Estou acompanhando pra achar brechas para ajudar (as que são compativeis com meu background)

**Comment by woliveiras** [comment]
Shoooow @ogilvieira

**Comment by daniloagostinho** [comment]
@ogilvieira então somos 2 meu caro, estou só bizoando para poder ajudar, e aprender também! :heavy_check_mark:

**Comment by ogilvieira** [comment]
Como estou chegando agora, vou esperar a estrutura e assim pegar umas issues pra resolver emcima xD

**Comment by andre-mendes** [comment]
@ogilvieira somos 3 hahaha :D

**Comment by daniloagostinho** [comment]
@ogilvieira acho que devemos deixar de bobagem e começar a palpitar, eu tenho bastante ideia... 

O problema é por isso pra fora!

:sweat_smile:

**Comment by daniloagostinho** [comment]
:eyes:

**Comment by YuriBrunetto** [comment]
Todos estamos só na espreita 👍  hahahah

**Comment by daniloagostinho** [comment]
@YuriBrunetto podes crê! ;)

**Comment by baltazarparra** [comment]
@danilovaz @woliveiras e outros manos... to em divida pra caralho com o projeto, peço desculpa novamente, to trampando numa refatoração infinita e tá osso descola tempo, mas, vamo lá.

Qual status atual, vamos tocar essa bagaça agora, temos um canal pra trocar ideia fora daqui?

**Comment by woliveiras** [comment]
Fala @baltazarparra! Geral está em atraso aqui mano.

Estamos completamente sem tempo para os projetos paralelos. Podemos conversar lá no Slack. Chama a gente lá que crio o canal. :smile:

**Comment by baltazarparra** [comment]
é pra já @woliveiras, te chamei lá.

**Comment by danilovaz** [comment]
@baltazarparra relaxa, tá uma correria mesmo desde o fim do ano, sei como é. @woliveiras me envolve nesse canal aí, tô voltando agora aos poucos e consigo ajudar mais :heart:

**Comment by baltazarparra** [comment]
@danilovaz nóis o/ (antes das 18h é foda, mas depois, tamo ai pa troca aquela ideia)

**Comment by woliveiras** [comment]
Hoje eu consigo entrar lá pra gente conversar, também, galera! :smile:

**Comment by YuriBrunetto** [comment]
Se tiver como, também me interesso em entrar nesse canal @woliveiras 😄

**Comment by nandomoreirame** [comment]
:metal:

**Comment by baltazarparra** [comment]
Toda ajuda, será MUITO bem-vinda @YuriBrunetto

**Comment by karolinedealencar** [comment]
Podem me colocar também? <3 <3

**Comment by danilovaz** [comment]
o @YuriBrunetto tá voando :heart:

**Comment by felipeorlando** [comment]
Galera, se precisarem de um back-end, me avisem! Tô disponível! :wink:

**Comment by YuriBrunetto** [comment]
@danilovaz @baltazarparra vamoooo timeeee ❤️

**Comment by woliveiras** [comment]
Fala galera!

Criei um canal no nosso Slack: https://ctgroups.slack.com/messages/issues/

Pra gente discutir essa e outras issues do CT. Bora lá! 😄 

Quem ainda não estiver no Slack, pode me mandar o email que eu adiciono lá.

**Comment by karolinedealencar** [comment]
@woliveiras me colocaaa, karolinedalencar@gmail.com <3

**Comment by woliveiras** [comment]
Convite enviado @KarolinedeAlencar 😄

**Comment by baltazarparra** [comment]
Alguém curte arquitetura da informação aqui? Vou precisar de ajuda pra levantar o conteúdo que vai na home, baseado no layout que temos hoje nas issues. Quem pode assumir essa parte?

**Comment by nandomoreirame** [comment]
Eu posso pegar esse desafio brother 😁

Em 2 de fev de 2017 8:15 AM -0200, Baltazar Parra <notifications@github.com> escreveu:

**Comment by woliveiras** [comment]
Entra no canal #issues do Slack, @nandomoreirame 😄

**Comment by baltazarparra** [comment]
Perfeito mano @nandomoreirame 

Cola lá no slack pra gente desenrolar o projeto.

**Comment by woliveiras** [comment]
Conversamos via Slack, issues e Hangout e será feito um novo desenho para implementarmos a partir da semana que vem.

Essa issue não faz mais sentido para o nosso fluxo atual.
