### ISSUE TITLE
Layout

### ISSUE THREAD

**Issue by gustavom** [training-center/training-center.github.io#16]
Pessoa, 
Onde eu posso ver o layout do projeto?

Gostaria de tentar ajudar no código do projeto.

Valeu!

**Comment by woliveiras** [comment]
Aeeee, será uma ajuda muito bem vinda!

É esse aqui: https://github.com/training-center/training-center.github.io/issues/4#issuecomment-298696791

**Comment by woliveiras** [comment]
Se precisar de algo é só chamar a gente aqui de novo. 😄
