### ISSUE TITLE
Definição de funcionalidades/requisitos do projeto

### ISSUE THREAD

**Issue by woliveiras** [training-center/training-center.github.io#2]
Conforme alinhado na issue #1 definimos separar os tópicos da issue em outras issues mais específicas.

Essa issue é para levantamento das funcionalidades do nosso site.

Inicialmente temos:

Um site com uma home page estilo langing page com as informações sobre o Training Center de uma maneira convidativa para as pessoas se interessarem a ajudar outras pessoas através do projeto ou apoiarem o projeto de alguma maneira.

Dentro desse site teremos duas páginas, uma para cada projeto principal do Training Center (Mentoria e Study Groups).

Ambas as páginas tem funcionalidades parecidas:
- A página do Mentoria deve listar os Mentores e Pupilos e possuir filtros para ordenar por `Mentores que estão aceitando novos pupilos`/`pupilos que estão buscando mentoria`
- A página do Study Groups deve ser outra landing page explicando a ideia de se estudar em grupo e listar os grupos (canais do Slack) que já existem

Caso alguém queira especificar mais alguma funcionalidade que seria interessante, devemos conversar nessa issue.

**Comment by danilovaz** [comment]
Acredito que uma boa forma de listar os mentores e quem precisa de mentoria, seria como o @ogilvieira fez no [Awesome Podcasts BR](http://ogilvieira.com.br/awesome-podcasts-br/#/)

**Comment by woliveiras** [comment]
Siiiim! É uma boa.

**Comment by ogilvieira** [comment]
Legal, pensei em algo como "Encontre seu mentor" e listar os mentores com características das tecnologias ou conceitos em que eles sejam voluntários. Acho que é mais fácil eu encontrar um mentor do que um mentor entender o que eu preciso dele hehe

**Comment by woliveiras** [comment]
Interessante esse ponto de vista @ogilvieira 

Nunca havia parado pra pensar nisso

**Comment by daniloagostinho** [comment]
:eyes:

**Comment by baltazarparra** [comment]
@woliveiras Cara, o que eu preciso é dessas definições aqui, o que vamos ter na Home do projeto? Funcionalidades e informações... Só preciso desse levantamento de informação pra começar o layout.

Vamos lá, na home, vamos colocar informações sobre o CT, uma sessão sobre os 'Study-groups', uma sessão sobre o 'Mentoria', link para nosso slack, informações sobre os parceiros, redes sociais, acho que seria legal uma listagem dos posts recentes no medium, listagem para as entrevistas também, separado... O que mais?

**Comment by woliveiras** [comment]
\o/

@baltazarparra eu posso fazer esse levantamento e te mandar até amanhã a noite?

**Comment by baltazarparra** [comment]
Opa! Demoro @woliveiras, fico no aguardo!

**Comment by woliveiras** [comment]
Show mano.

Valeu! 😄

**Comment by woliveiras** [comment]
@baltazarparra 

Pensei em deixarmos algo simples e fazer um MVP, afinal precisamos do projeto rápido para começar a indexar e as pessoas conhecerem.

Podemos fazer estilo o freeCodeCamp: https://www.freecodecamp.com/

Na home:

- uma descrição do que é o projeto
- uma lista gigante do que a pessoa pode aprender partindo desde web ao infinito e além de badges (pode ser estilo aqueles badges que eles colocam no site do fcc) 
- uma descrição de como participar da nossa comunidade (da `comunidade`, não somente do Mentoria)

links no header:

- blog (https://medium.com/trainingcenter)
- chat pra ser mais convencional pra quem não conhece o slack (https://ctgroups.herokuapp.com)
- sobre nós (link para um post mais elaborado que vou escrever no Medium)
- github (https://github.com/training-center/)
- mentoria (um post também no medium que vou explicar o que é o Mentoria)
- `@trainingcentr` (um link para nosso twitter: https://twitter.com/trainingcentr)

Ai, para uma segunda versão do site nós fazemos algo mais elaborado e se você quiser já pode até deixar essa segunda versão preparada para codarmos e vamos incrementando o site. 😄

Você vai precisar dos textos?

Eu posso fazer agora mesmo pra você.

**Comment by khaosdoctor** [comment]
eu acho que uma boa ideia para a página da mentoria é criar tipo uma rede (isso, óbvio, estou falando mais para frente para podermos montar certinho) mas se conseguirmos pegar todos os mentores que estão já com pupilos, quais são estes pupilos, podemos montar um grafo bem bacana ou algum esquema de lista que mostra quais são todos os mentores disponíveis e quais pupilos eles já tem, além de mostrar um "espaço vazio" se o cara estiver aceitando mais alguém.

Selecionando os mentores, poderíamos ver os projetos desenvolvidos com os pupilos, ou as tecnologias que este mentor está disposto a ajudar.

Isto tudo para poder realmente deixar uma coisa bem legal e bem visivelmente conectada, para dar aquela ideia e passar a mensagem de que desenvolvimento não é você sozinho no quarto, mas sim uma comunidade de humanos para humanos.

**Comment by baltazarparra** [comment]
@woliveiras Perfeito mano, vamos fazer esses textos já sim, se precisar de um help chama slack ;)
Cara, o que acha de uma sessão explicando um pouco sobre os Grupos de Estudo e o projeto Mentoria? Fora isso, uns cards com posts do Medium, acho que cairia bem também, ai a gente ia centrar quase todo conteúdo do TC em uma page.

**Comment by woliveiras** [comment]
@khaosdoctor, vai surgir uma plataforma pro Mentoria mano

O bagulho vai ser LOKO

kkkkkk

Pra esse site, por enquanto, o importante é só ter informações centralizadas sobre o Training Center e links para nossas iniciativas. Assim como é esse repositório, só que em um site e mais bonito com o design do nosso querido @baltazarparra monstrão. 😄

**Comment by woliveiras** [comment]
Acho super interessante colocar os cards e até o esquema do Twitter que você mencionou viu @baltazarparra 

Mas é legal fazer em ideia de MVP, fazemos algo bem simples que podemos construir rapidinho pra já ter gente chegando lá. Depois melhoramos com os cards e tudo mais.

Sobre as sessões, você diz no meio da página mesmo?

O usuário vai rolando a página e descobre sobre o Mentoria e Grupos de Estudos?

**Comment by baltazarparra** [comment]
Concordo sobre o MVP @woliveiras, por isso pensei em algo simples mesmo, pode até ser estático, um link pro github... só pra facilitar, o cara entra no site, lê sobre as iniciativas e já linkamos ele na cara do gol kkk.

**Comment by woliveiras** [comment]
Fala, galera!

Essa issue já deveria ter sido fechada.

Perdão.

Obrigado a todas as pessoas que ajudaram!
