### ISSUE TITLE
Data Tracking e Analytics

### ISSUE THREAD

**Issue by vicainelli** [training-center/training-center.github.io#20]
Galera, não sei se alguém já pensou/fez isso.

Mas o que acham de colocar, pelo menos, um tracking go Google Analytics no site?

Assim da pra saber qual tipo de publico o site vai ter que atender.

**Comment by woliveiras** [comment]
Acho uma boa, @vicainelli 

Não colocamos ainda por vacilo meu mesmo.

**Comment by vicainelli** [comment]
Se já tiver a conta go GA, coloca os códigos aqui na issue que alguém, ou eu mesmo coloco.

**Comment by YuriBrunetto** [comment]
Ótima ideia

Podemos colocar o código e deixar comentado, aí quando lançarmos o site a gente ativa 😄

**Comment by adeonir** [comment]
Opa... Isso, usar o GA somente quando o site for pra produção.

**Comment by vicainelli** [comment]
@YuriBrunetto @adeonir pq só quando estiver em produção?
Tem algum motivo especifico para não coletar os dados a partir de agora?

**Comment by khaosdoctor** [comment]
Acho que a gente pode colocar no site que já está online agora assim ficamos sabendo o que está acontecendo nele

**Comment by YuriBrunetto** [comment]
@vicainelli não tem nenhum motivo específico eu acho.. mais porque muitas vezes iremos entrar nele agora pra testar e ia ir contando as visitas "a toa". Ou não né auhauuahuauh 😄  vcs que sabem

**Comment by vicainelli** [comment]
E quando o site for lançado não iremos testar, e gerar visitas "a toa" também? rs
Eu acho uma boa colocar desde já, assim já vai rastreando tudo, inclusive, nossos acessos de testes.

**Comment by YuriBrunetto** [comment]
@vicainelli de acordo! ehhehehe beleza 😺

**Comment by woliveiras** [comment]
Galera, foi adicionado aqui: #32
