### ISSUE TITLE
Definição das tecnologias a serem utilizadas no projeto

### ISSUE THREAD

**Issue by woliveiras** [training-center/training-center.github.io#3]
Conforme alinhado na issue #1 definimos separar os tópicos da issue em outras issues mais específicas.

Uma estrutura básica já foi citada na issue na sessão `Estrutura` onde:
- Um arquivo JSON vai receber os dados dos Mentores que serão preenchidos via PR pelos próprios novos Mentores.
- Tendo o arquivo, um esquema de template renderiza a lista com paginação, filtros e uma boa usabilidade para o usuário final
- Devemos seguir o esquema das labels ([Mentoria](https://github.com/training-center/mentoria/labels), [Study Groups](https://github.com/training-center/study-groups/labels)) para os filtros no site para haver consistência entre o que já fazemos com o novo fluxo

Como no projeto `Eventos` do [FrontEndBR](https://github.com/frontendbr/eventos/issues/3).

Na issue chegamos a "conclusão" de se usar React para os templates e podemos contar com a ajuda/coordenação do @matmarsiglio para isso

Nessa issue devemos discutir aspectos técnicos do projeto como qual task runner usar, estrutura de diretórios, etc

**Comment by danilovaz** [comment]
Let's do it?

Alguém tem alguma ideia de por onde exatamente começar? :laughing:

**Comment by woliveiras** [comment]
O @matmarsiglio manja dos esquemas!

Se for interessante ele pode já ir tacando pau na estrutura do projeto (adicionar webpack, as tarefas comuns pra trabalhar com React, etc).

**Comment by daniloagostinho** [comment]
Eu usaria o Gulp, acho bem mais simples a configuração dele, e sem falar nas possibilidades de integração com outras libs. 

O que vcs acham?

**Comment by ghost** [comment]
Se for para trabalhar com React é menos trabalhoso usar webpack ao invés de gulp na minha opinião.

**Comment by woliveiras** [comment]
Foi pelo que o @wesleycoder falou mesmo @DaniloAgostinho. :)

Mais fácil seguir o fluxo adicionando webpack pra facilitar a interação com o React.

**Comment by mtmr0x** [comment]
O Webpack para stylesheets não é a coisa mais bonita do mundo, conseguimos usar os dois. Consigo configurar uma forma automatica de rodar tudo de uma vez só com um script simples dentro do `package.json`, onde roda o servidor, webpack e gulp para os stylesheets.

Aí seria: 

```
$ npm run dev
```

e seria responsável por rodar:

``` bash
$ jekyll serve
$ gulp
$ gulp watch
$ webpack --watch
```

**Comment by daniloagostinho** [comment]
@woliveiras então tá certo, bacana esse desenrolar :eyes:

**Comment by daniloagostinho** [comment]
@matmarsiglio :clap:

**Comment by woliveiras** [comment]
Shoooow @matmarsiglio 

Taca pau!

**Comment by woliveiras** [comment]
Depois de algumas atualizações na ultima semana chegamos a conclusão de utilizarmos Jekyll e HTML+CSS simples para incluirmos pessoas mais iniciantes no desenvolvimento e manutenção do site
