### ISSUE TITLE
Atualização do site

### ISSUE THREAD

**Issue by crisgon** [training-center/training-center.github.io#39]
Olá, pessoal! Queria saber se vocês estão com algum plano  de reformulação do site? Pois tem muitas iniciativas novas que começamos e não constam no site ainda. Inclusive o site ainda está com a logo antiga, acredito eu.

**Comment by woliveiras** [comment]
Fala, @crisgon 

Temos sim! \o/

O time de design está para criar um site totalmente novo, com mais informações e baseado no que falta de centralização de conteúdo da nossa comunidade. Então vai vir algo bem maneiro de se trabalhar em cima logo logo.

OBS: pra mudar o logo antigo teríamos que reformular o site, pois não bate :joy: 

Você se interessaria em contribuir com código ou design na reformulação?

**Comment by crisgon** [comment]
Tenho interesse em contribuir com a reformulação!! :smile:

**Comment by woliveiras** [comment]
Vou avisar o time de design pra galera entrar em contato contigo, manoooo

**Comment by khaosdoctor** [comment]
@woliveiras Vou fechar a issue aqui tudo bem? Continuamos no Slack 😄
