### ISSUE TITLE
Atualização/Modificações no Layout para adicionar novos requisitos

### ISSUE THREAD

**Issue by woliveiras** [training-center/training-center.github.io#4]
Conforme alinhado na issue #1 definimos separar os tópicos da issue em outras issues mais específicas.

Os requisitos estão sendo levantados na issue #2. Assim que a mesma estiver dada por finalizado, pode-se existir alterações no [layout](http://baltazarparra.github.io/ct-layout.html) (:metal:) que já possuímos criado pelo @baltazarparra e vamos utilizar essa issue para discussões sobre essas modificações.

**Comment by nandomoreirame** [comment]
👍

**Comment by baltazarparra** [comment]
Quando definirmos o escopo das features, vou voltar pro layout e alterar oque alinharmos, ok? Não vou poder acompanhar tão de perto as outras issues, então fico no aguardo do desenrolar.

Vou liberar o psd tb, caso alguém queira ajudar com o Design Visual / Usabilidade, será muito bem vindo!

**Comment by woliveiras** [comment]
Boa @baltazarparra 

Liberando o PSD fica mais fácil de outros manjadores das artes do Design alterarem também

Sucesso!

**Comment by baltazarparra** [comment]
PSD liberado no meu fork.

https://github.com/baltazarparra/training-center.github.io

E como o Zeplin estava de mal humor hoje cedo, joguei no assets tb.

http://adobe.ly/2efTsdT

Obs. Perdão pela bagunça nas layers.

**Comment by woliveiras** [comment]
Show mano!

Creio que não vá aparecer nenhum novo recurso na #2.

Se quiser, pode tacar lenha nas interfaces internas (Mentoria e Study Groups) que já vamos começar a codar! :raised_hands:

**Comment by daniloagostinho** [comment]
Que emoção poder ver o desenrolar de um projeto open source, porque não fiz isso antes, sim bora!

:metal:

**Comment by jlucfarias** [comment]
O layout pra desktop tá ótimo, mas é pro mobile?

**Comment by baltazarparra** [comment]
Na real @John-Luke esse desk ai é mobile-first, mas n lembro onde postei a versão mobile, mas indiferente disso, faz um bom tempo que foi criado e quero tratar algumas coisas diferentes, então vou pegar esse fds pra refazer ele.

**Comment by adeonir** [comment]
O que tem em mente?

**Comment by woliveiras** [comment]
Mentira, @baltazarparra 

Vai mesmo mano? 

Então precisamos repensar na estrutura... Mudaram algumas coisas que podem até facilitar a vida 

Se você for fazer no final de semana, podemos planejar tudo isso em conjunto. 

Fazemos um Hangout com a galera que está participando aqui da thread e conversamos sobre o que precisamos ter no site e eu já crio a estrutura com Jekyll e depois é só codar o front.

O que acham, pessoal?

**Comment by woliveiras** [comment]
Venha pra cá @alinebastos

**Comment by karolinedealencar** [comment]
Opa @woliveiras, acho bacana a ideia! Só ver c o resto da galera =)

**Comment by baltazarparra** [comment]
Bora lá \o/ galero

**Comment by woliveiras** [comment]
Galera, topam o hangout as 14 no sábado?

cc: @baltazarparra @KarolinedeAlencar @adeonir @John-Luke @DaniloAgostinho @khaosdoctor @felipeorlando @irwing-max @MarianoJhuninhu @lflimeira @alinebastos

**Comment by alinebastos** [comment]
Não fui mencionada mas topo :P haha

**Comment by jlucfarias** [comment]
Esse fim de semana vai ser difícil de eu conseguir participar, mas talvez no próximo

**Comment by karolinedealencar** [comment]
Opa! Por mim tudo bem, bora lá @alinebastos hahah

**Comment by adeonir** [comment]
Sábados à tarde sempre tenho compromisso, pode ser de manhã ou à noite.

**Comment by MarianoJhuninhu** [comment]
@woliveiras, Talvez ainda vou estar no Dentista.

**Comment by woliveiras** [comment]
Se a maioria puder de manhã, podemos marcar para umas 10:00, seria legal?

**Comment by woliveiras** [comment]
@YuriBrunetto

**Comment by khaosdoctor** [comment]
@woliveiras opa! Posso em ambos os dias, estou no período "entre empregos" então não trabalho amanhã, estou tranquilo para um hangout. Só preciso da confirmação kkk

**Comment by baltazarparra** [comment]
As 10h é miado pra mim, =s só vou estar ON depois do 12h no sábado.

**Comment by adeonir** [comment]
Às 12h tá tranquilo pra mim. Posso ficar até 13h30, se não conseguirmos ver tudo, vocês continuam sem mim.

**Comment by khaosdoctor** [comment]
Eu estou online hoje aqui, mas acho então que fica melhor a gente marcar no sabado, o que acham @baltazarparra, @adeonir, @woliveiras

**Comment by woliveiras** [comment]
As 13:00 é um bom horário pessoal?

**Comment by YuriBrunetto** [comment]
Olá queridos!

Não vou estar na cidade amanhã... 😢 
Mas, comentem na issue um resumo do que for discutido e eu ajudarei no que for preciso! 👍

**Comment by woliveiras** [comment]
😢

**Comment by woliveiras** [comment]
@baltazarparra @KarolinedeAlencar @adeonir @John-Luke @DaniloAgostinho @khaosdoctor @felipeorlando @irwing-max @MarianoJhuninhu @lflimeira @alinebastos conseguimos conversar as 13:00?

**Comment by woliveiras** [comment]
Conversei com o @baltazarparra por hangout e ele já vai bolar a landing pra gente!

Até segunda teremos tudo preparado e eu já farei a modelagem do conteúdo via Jekyll galera.

Agora vai!!!

**Comment by MarianoJhuninhu** [comment]
foi mal ai acabou que o dente demorou mais que o esperado

**Comment by woliveiras** [comment]
Sem problemas @MarianoJhuninhu 

Fizemos uma chamada e o @baltazarparra irá nos enviar uma nova proposta de layout até segunda feira. 😄 

Com esse desenho em mãos eu consigo preparar o Jekyll servindo as informações na tela e então é só codar o front.

**Comment by YuriBrunetto** [comment]
Show de bola, pessoal! Estou ansioso para ver o resultado :smile:

**Comment by khaosdoctor** [comment]
Caras vamos abrir um canal no slack pra isso? Eu não consigo ver muito por aqui 😸 o que diz @woliveiras ?

**Comment by woliveiras** [comment]
Pra discussões desse tipo é melhor conversar pelas issues pra não perder o histórico, @khaosdoctor 😄 

Mas eu posso te dar um grito no Whats quando tivermos reunião de novo pra você não perder, o que acha?

**Comment by khaosdoctor** [comment]
@woliveiras Cara seria muito sensacional porque eu sou um cara extremamente esquecido das coisas kkk

**Comment by lflimeira** [comment]
@woliveiras  Eu acabei perdendo tbm, pq eu acabei não acessando por aqui, a ideia de dar um toque pelo telegram ou algum lugar que lembre me agrada tbm kkk

**Comment by woliveiras** [comment]
Galera, o @baltazarparra já está confirmado no time de mantenedores do site.

Alguém de vocês gostaria de firmar esse compromisso também?

Vou criar um time para essas pessoas no Telegram, adicionar na Org aqui no GitHub e dar acesso total ao repositório, por isso a pergunta.

**Comment by YuriBrunetto** [comment]
@woliveiras eu!! Durante a semana tô disponível sempre. 😃

**Comment by lflimeira** [comment]
@woliveiras  eu tbm gostaria de participar.

**Comment by adeonir** [comment]
Ae @woliveiras, do que precisa para completar o time?

**Comment by woliveiras** [comment]
Shoooow!!! 

Me informem seus usuários do Telegram, por favor.

**Comment by woliveiras** [comment]
O @baltazarparra enviou uma nova versão:

![novo-layout-training-center](https://cloud.githubusercontent.com/assets/4243601/25629428/d6b91e0e-2f3f-11e7-9dd4-bfc2cf757cc7.jpg)

Então eu criei uma estrutura usando Jekyll e HTML simples para que pessoas em qualquer nível de conhecimento consiga contribuir: https://github.com/training-center/training-center.github.io/tree/dev

**Comment by woliveiras** [comment]
@adeonir só da confirmação de quem quer ficar responsável pelo projeto mesmo.

Já tenho confirmação do @baltazarparra :)

**Comment by adeonir** [comment]
Confirmado.

**Comment by karolinedealencar** [comment]
Posso entrar no time tb? :)

**Comment by lflimeira** [comment]
O meu user é @lflimeira.

**Comment by woliveiras** [comment]
Pode sim, @KarolinedeAlencar 

Qual seu usuário no Telegram?

**Comment by karolinedealencar** [comment]
É @karolinedealencar

**Comment by YuriBrunetto** [comment]
Meu user no Telegram é @ybrntt

**Comment by ftonato** [comment]
Eu tô por fora do que está acontecendo aqui, mas eu queria falar com alguém que tenha a habilidade de desenhar para eu mostrar algo e essa pessoa "me ajudar a desenhar" uma ideia que eu tive aqui =)

Se tiver alguém aí que quiser me ajudar, me avisa que vamos montar um outro layout e depois poderíamos fazer uma votação dos layouts e ver qual o pessoal mais gosta.

/cc @woliveiras

**Comment by gabriel-brito** [comment]
O Layout ficou show! Tô ansioso pra ver as novidades do CT :smile:

**Comment by alinebastos** [comment]
Me adiciona tb, @woliveiras o/

**Comment by woliveiras** [comment]
Nós já começamos o desenvolvimento desse layout @ftonato 

Será que consegue fazer essa versão até segunda feira que vem?

Eu já montei o "back end" e o @baltazarparra já vai tocar lenha no front na semana que vem.

**Comment by ftonato** [comment]
@woliveiras  Deixamos assim então, e assim que eu tiver tempo submeto uma nova proposta =)

**Comment by khaosdoctor** [comment]
O site vai ser desenvolvido com o Jekyll mesmo?

**Comment by woliveiras** [comment]
Perfeito @ftonato, vamos mudar muito esse site ainda! 😄

**Comment by woliveiras** [comment]
Isso, isso, isso, @khaosdoctor 

Por que é uma abordagem mais fácil pra pessoas com pouco conhecimento. Assim podemos trazer os pupilos pra contribuir. 😄

**Comment by khaosdoctor** [comment]
Ah então beleza, me coloca nesse repo ai que depois eu te chamo no slack e ai podemos definir que talvez eu possa ajudar sim 😄

**Comment by woliveiras** [comment]
Já me mande seu usuário do Telegram, @khaosdoctor 🤘

**Comment by khaosdoctor** [comment]
É lhs_santoss @woliveiras

**Comment by woliveiras** [comment]
Adicionado manooo

**Comment by adeonir** [comment]
Segue arquivo do layout em PSD: [tc-layout.zip](https://github.com/training-center/training-center.github.io/files/1005934/tc-layout.zip)

**Comment by khaosdoctor** [comment]
Vou adicionar no repositório principal aqui pra todo mundo poder ter ele
