### ISSUE TITLE
Criação da estrutura inicial

### ISSUE THREAD

**Issue by woliveiras** [training-center/training-center.github.io#5]
Criação da estrutura inicial do projeto com as tecnologias especificadas na #3 
## Checklist
- [ ] Criação dos diretórios
- [ ] Configuração de task runner
  - [ ] server local
  - [ ] build
  - [ ] deploy
- [ ] estrutura inicial do projeto

**Comment by nandomoreirame** [comment]
👍

**Comment by daniloagostinho** [comment]
ótimo! 👍

**Comment by woliveiras** [comment]
Galera, estava pensando em fazer esse site usando o Jekyll.

Existe esses esquema maneiro aqui: https://www.smashingmagazine.com/2016/02/content-modeling-with-jekyll/

Podemos usar isso pra colocar o conteúdo.

O que acham?

**Comment by nandomoreirame** [comment]
acho toper :top:

**Comment by jlucfarias** [comment]
Eu nunca trabalhei com Jekyll, mas tô aqui pra ajudar com o que for preciso

**Comment by nandomoreirame** [comment]
Jekyll é amor :heart_eyes:

**Comment by karolinedealencar** [comment]
Opa, tb to dentro! =)

**Comment by woliveiras** [comment]
Assim que se fala @John-Luke!! \o/

**Comment by woliveiras** [comment]
Na issue #4 o @baltazarparra comentou que vai refazer o design, então levantei o ponto de fazermos um Hangout, bora falar sobre isso lá galera?

**Comment by woliveiras** [comment]
Depois de algumas atualizações na ultima semana chegamos a conclusão de utilizarmos Jekyll e HTML+CSS simples para incluirmos pessoas mais iniciantes no desenvolvimento e manutenção do site
