### ISSUE TITLE
a11y - Remover target="_blank" dos links

### ISSUE THREAD

**Issue by robertoachar** [training-center/training-center.github.io#51]
Pessoal, como [solicitado pelo William](https://twitter.com/w_oliveiras/status/1004411490735140871), estou abrindo essa issue para remover os `target="_blank"` dos links do site do Training Center.

Esse atributo não é recomendado pois pode gerar alguns problemas de acessibilidade para pessoas com dificuldades em navegar pela Internet.

Entre outros problemas, alguns são:

1. Ocorrer desorientação quando uma nova janela se abrir
2. Não existe o "Botão Voltar" como temos no browser
3. Alguns equipamentos não permitem abrir novas janelas

A melhor opção seria remover esse atributo e deixar que as pessoas escolham se querem ou não abrir o conteúdo do link em uma nova janela/aba.

Essa é uma issue que considero **good first issue** e acredito que seja uma ótima oportunidade para um iniciante tentar enviar o PR.

Me coloco a disposição, não só pra esclarecer mais sobre o assunto, quanto para auxiliar na criação do PR.

**Comment by khaosdoctor** [comment]
Foi resolvido no #52, aguardando mesclagem. Vou fechar por aqui!
