### ISSUE TITLE
Desenvolvimento da aplicação

### ISSUE THREAD

**Issue by woliveiras** [training-center/training-center.github.io#7]
Desenvolvimento da integração com APIs, filtros e paginação.
## Checklist
- [ ] Script pra ler o JSON e renderizar o template
- [ ] Script pra filtros (labels aqui do repo, preço, local)
- [ ] Paginação

Aguardando maiores definições na #3

**Comment by nandomoreirame** [comment]
👍

**Comment by daniloagostinho** [comment]
👍

**Comment by woliveiras** [comment]
Essa issue será fechada para atualização do repositório
